security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: users_in_memory
            logout:
                path: app_logout
                target: /